# Introduction to Statistical Learning 

# 1.Introduction 

# 2. Statistical Learning

## <span style="color:red"> 2.1 What is Statistical Learning ?</span>.

- <b>$X1$</b>, <b>$X2$</b>, <b>$X3$</b>, ... , <b>$Xp$</b> : Input variable,predicators, independent variables, features, variables
  <b>$Y$</b> : Dependent variable 
- Relationship between Y and X = (<b>$X1$</b>, <b>$X2$</b>, <b>$X3$</b>, ... , <b>$Xp$</b>) can be written in general form :
  <b>$Y$</b> = $f$(<b>$X$</b>) + $\epsilon$
    - $\epsilon$ : random error term which is independent of $X$ and has $mean$ zero
    - $f$ is the binding between the dependent and independent variables but that fuction is unknown heence there is a need to $estimate f $ based   on the observed points.
- Statistical learning : Set of approaches for estimating $f$
___


### <span style="color:blue"> 2.1.1 Why estimate $f$</span>.

Reason to estimate $f$
1. Prediction 
2. Inference

#### 1. Prediction

- In many situations, a set of inputs $X$ are readily available, but the output
$Y$ cannot be easily obtained. In this setting, since the error term averages
to zero, we can predict $Y$ using : <br>
   
  $\hat Y$ = $\hat f$($X$)<br>
  $\hat Y$ : resulting prediction/estimation for $Y$ <br>
  $\hat f$ : resulting prediction/estimation for $f$

- In this setting, $\hat f $ is <b>often treated as a black box</b>, in the sense
that one is not typically concerned with the exact form of $\hat f $, provided that
it yields accurate predictions for $Y$ .
- The accuracy of   $\hat Y$ as a prediction for $Y$ depends on two quantities,which we will call the reducible error and the irreducible error. 
- $f$  will not be a perfect estimate for f, and this inaccuracy will introduce some error.
- reducible error : we can potentially improve the accuracy of $\hat f$($X$) by using the most appropriate statistical learning technique to estimate $f$.
- we have <b>$Y$</b> = $f$(<b>$X$</b>) + $\epsilon$
- irreducible error : This is because $Y$ is also a function of epsilon, which, by defnition, cannot be predicted using $X$. Therefore, variability associated with " also afects the accuracy of our predictions.

<img src="img_1.JPG" alt="image" width="500" height="auto">

- $E$($Y$ - $\hat Y$)$^2$ : represents the expected value (mean) of the squared difference between the actual $Y$ and predicted $\hat Y$.
- Var($\epsilon$) : denotes variance associated with the error term 

NOTE : irreducible error will always provide an upper bound on the accuracy of our prediction for $Y$ . This bound is almost always unknown in practice.

___

#### 2. Inference 

- We are often interested in understanding the association between $Y$ and
$X1,...,Xp$. 
- In this situation we wish to estimate $f$, but our goal is not
necessarily to make $predictions$ for $Y$ . Now <b> $\hat f$  cannot be treated as a black
box, because we need to know its exact form.</b>


<img src="img_2.JPG" alt="image" width="600" height="auto">


Img description : The Advertising data set. The plot displays sales, in thousands
of units, as a function of TV, radio, and newspaper budgets, in thousands of
dollars, for 200 diferent markets. In each plot we show the simple least squares
ft of sales to that variable, as described in Chapter 3. In other words, each blue
line represents a simple model that can be used to predict sales using TV, radio,
and newspaper, respectively

___

##### Example including both $prediction$ and $inference$

real estate setting, one may seek to relate values of homes to inputs :
- crime rate 
- zoning
- distance from a river 
- air quality
- schools 
- income level of community
- size of houses
 </br>
 
 <u>$inference$</u> : <span style="color:green">association between each <i>individual input variable</i> and <i>housing price </i> </span> for instance, <b>how much extra will a house be worth if it has a view of the river?</b> </br>
<u>$prediction$</u> : <span style="color:green">predicting the value of a
home given its characteristics:  </span><b>is this house under- or over-valued?</b>

___

> NOTE :  In contrast, some of the highly non-linear approaches
that we discuss in the later chapters of this book can potentially provide
quite accurate predictions for Y , but this comes at the expense of a less
interpretable model for which inference is more challenging

___

### <span style="color:blue"> 2.1.2 How do we estimate $f$ ?</span>

- Assumption : We will always assume that we have observed a set of n diferent data points
- training data because we will use these observations to train, or teach, our method how to estimate $f$. 

- $xij$ : value of $j$ th predictor for $i$ th observation 

<img src="img_3.JPG" alt="image" width="700" height="auto">

- $y_i$ : response variable for the $i$th observation.
- Then our training data consist of :

<img src="img_5.JPG" alt="image" width="600" height="auto">
<img src="img_4.JPG" alt="image" width="500" height="auto">
<br>
<br>
Our goal is to apply a statistical learning method to the training data
in order to estimate the unknown function $f$. In other words, we want to
fnd a function $\hat f $ such that Y ≈ $\hat f $ for any observation ($X$ , $Y$). <br>Broadly
speaking, most statistical learning methods for this task can be characterized as either <b>$parametric$</b> or <b>$non-parametric$</b> 

___


#### <span style="color:blue"> Parametric Method</span>.

- two-step model-based approach.
1. First, we make an assumption about the functional form, or shape, of $f$. For example, one very simple assumption is that <b> f is linear in </b> X 

   #### $f$($X$) ≈ $\beta_0$ + $\beta_1$ $X_1$ + $\beta_2$ $X_2$ + ··· + $\beta_p$ $X_p$.

    - Instead of having to estimate an entirely arbitrary $p$ -dimensional function $f$($X$), one only needs to estimate the $p + 1$ coefcients $\beta_0$, $\beta_1$, $\beta_2$, . . . , $\beta_p$
2. After a $linear \; model$ has been selected, we need a procedure that uses the training data to fit or train the model. In the case of the linear model fit, we need to estimate the parameters $\beta_0$, $\beta_1$, $\beta_2$, . . . , $\beta_p$. That is, we want to find values of these parameters such that : <br>
    #### $Y$ ≈ $\beta_0$ + $\beta_1$ $X_1$ + $\beta_2$ $X_2$ + ··· + $\beta_p$ $X_p$.
    
___

<img src="img_7.JPG" alt="image" width="500" height="auto"> <img src="img_8.JPG" alt="image" width="500" height="auto">

___

- Most common approach to fit linear model is method of least square methods but there are other approaches to fit the linear model

> NOTE:
1. The model-based approach is referred to as parametric; it reduces the problem of estimating $f$ down to one of estimating a set of $\beta_0$, $\beta_1$, $\beta_2$, . . . , $\beta_p$ parameters.Since we assume $f$ a parametric form of above mentioned parameters in linear model.
2. disadvantage of a parametric approach is that the model we choose will usually not match the trueunknown form of f.
3. We can try to address this problem by choosing fexible models that can fit many diferent possible functional forms fexible for f. But in general, ftting a more fexible model requires estimating a greater number of parameters. These more complex models can lead to a phenomenon known as $overftting$ $the$ $data$, which essentially means they $overftting$ follow the errors, or noise, too closely.

___

<img src="img_8.JPG" alt="image" width="600" height="auto">
Fitted linear model : <img src="img_9.JPG" alt="image" width="500" height="auto">

---

#### <span style="color:blue"> Non-Parametric Method</span>.

- does not assume any form of $f$
- they seek an estimate of f that gets as close to the data points as possible.
-  by <b>avoiding the assumption of a particular functional form for </b> $f$ , they have the potential to accurately fit a wider range of possible shapes for $f$.
- Disadvantage : since they do not reduce the problem of estimating $f$ to a small number of parameters, a very large number of observations (far more than is typically needed for a parametric approach) is required in order to obtain an accurate estimate for $f$.

---

A thin-plate spline is used to estimate f. This approach does not impose any pre-specifed model on $f$ . It instead attempts to produce an estimate for f that is as close as possible to the observed data, subject to the ft—that is, the yellow surface as shown in the figure below : 
<br>
<br>
<img src="img_10.JPG" alt="image" width="600" height="auto">

---

##### Example of <b>overftting</b> : 
Undesirable situation because the ft obtained will not yield accurate estimates of the response on new observations that were not part of the original training data set.
<br>
<img src="img_11.JPG" alt="image" width="600" height="auto">

---

### <span style="color:blue"> 2.1.3 The trade-off between Prediction Accuracy and Model Interpritability  </span>

A representation of the tradeof between fexibility and interpretability, using diferent statistical learning methods. <br> In general, <b>as the fexibility of a method increases, its interpretability decreases.</b>

<img src="img_12.JPG" alt="image" width="800" height="auto">

---



 Why would we ever choose to use a more restrictive method instead of a very fexible approach?
- we are mainly interested in inference, then restrictive models are much more interpretable.
    -  when inference is the goal, the linear model may be a good choice since it will be quite easy to understand the relationship between $Y$ and $X_1$, $X_2$ ,...,$X_p$.

Sometimes if the Prediction is the goal then using Flexible model is of the use. (Sometimes less flexible model can alos achieve accurate prediction)

### <span style="color:blue"> 2.1.4 Supervised Versus Un-Supervised learning </span>

- Most statistical learning problems fall into one of two categories: supervised and unsupervised.

---

#### Supervised learning :
-  we have $x_i$ ,  $i$ = 1, 2, ... , $n$ observations for the predictor(s).
- there is an associated response $y_i$.
- here our aim is :
    -  to ft a model that relates the response to the predictors
    - Prediction 
        - accurately predicting the response for future observations 
    - Inference
        - better understanding the relationship between the response and the predictors
        
---

#### Un-Supervised learning :
- situation in which for every observation i = 1,...,n, we observe a vector of measurements $x_i$ but no associated response $y_i$. 
- It is not possible to ft a linear regression model, since there is no response variable to predict.
- we lack a response variable that can supervise our analysis.
- to understand the relationships between the variables or between the observations.
- One of the examples for doing un- supervised learning :
    - Cluster analysis or Clustering :
        - . The goal of cluster analysis cluster analysis is to ascertain, on the basis of $x_i$,...,$x_n$ whether the observations fall into relatively distinct groups
        - Example: 
            - market segmentation study we might observe multiple characteristics (variables) for potential customers,such as zip code, family income, and shopping habits
            - We might believe that the customers fall into diferent groups, such as big spenders versus low spenders.
            - . If the information about each customer’s spending patterns were available, then a supervised analysis would be possible.However, this information is not available—that is, we do not know whether each potential customer is a big spender or not.
            - In this setting, we can try to cluster the customers on the basis of the variables measured, in order to identify distinct groups of potential customers.
            - Identifying such groups can be of interest because it might be that the groups difer with respect to some property of interest, such as spending habits.
            - <i> A clustering data set involving three groups. Each group is shown using a diferent colored symbol. Left: The three groups are well-separated. In this setting, a clustering approach should successfully identify the three groups. Right: There is some overlap among the groups. Now the clustering task is more challenging<br>
</i> <img src="img_13.JPG" alt="image" width="600" height="auto">
                - goal is to determine the group to which each observation belongs.
                - We have plotted 150 observations with measurements on two variables, X1 and X2. Each observation corresponds to one of three distinct groups. For illustrative purposes, we have plotted the members of each group using diferent colors and symbols. However, in practice the <b>group memberships are unknown, and the goal is to determine the group to which each observation belongs.</b>
                - In the left-hand panel of the above fig, this is a relatively easy task because the groups are well-separated. By contrast, the right-hand panel illustrates a more challenging setting in which there is some overlap between the groups. A clustering method could not be expected to assign all of the overlapping points to their correct group (blue, green, or orange).
                - For instance, if there are p variables in our data set, then $p(p − 1)/2$ distinct scatterplots can be made, and visual inspection is simply not a viable way to identify clusters. For this reason, automated clustering methods are important.
            

### <span style="color:blue"> 2.1.5 Regression Versus Classifcation Problems </span>

- Variables 
    - Qualitative :
        - Categorical 
    -  Quantitative :
        - Numerical 
- Quantitative response : Linear Regression problems 
- Qualitative response : Classification problems (Logistic Regression*)
- We tend to select statistical learning methods on the basis of whether the <b>response</b> is quantitative or qualitative; i.e. we might use linear regression when quantitative and logistic regression when qualitative.
- whether the <b>predictors</b> are qualitative or quantitative is generally considered less important

## <span style="color:red"> 2.2 Assessing Model Accuracy</span>.

- it is an important task to decide for any given set of data which method produces the best results. Selecting the best approach can be one of the most challenging parts of performing statistical learning in practice.
-  we discuss some of the most important concepts that arise in selecting a statistical learning procedure for a specifc data set.

### <span style="color:blue"> 2.2.1 Measuring the Quality of Fit</span>

- Evaluating performance : How well the predicted results match with the actual results  : Least error 
- quantification of the extent to which the $predicted$ $response$ $value$ for a given observation is close to the $true$ $response$ $value$ for that observation.
- Regression setting :
    - Commmonly used setting : $Mean$ $Squared$ $Error$
        <br> <img src="img_14.JPG" alt="image" width="250" height="auto">
        - $\hat f(x_i) $ is the prediction that $\hat f $ gives for the ith observation
        - $MSE$ >> if actual response differs with the predicted response for some or many observations 
        - $MSE$ << if actual response does not much differ with the predicted response for given observations 
    - $Traning$ $MSE$ 
        - aboove mentioned MSEcomputed using the training data that was used to fit the model, and so should more accurately be referred to as the$Traning$ $MSE$.
- we do not really care how well the method works on the training data. Rather, we are interested in the <b>accuracy of the predictions that we obtain when we apply our method to previously unseen test data</b>
- Mathematical explanation :
    - Total observations = Training obs + Testing obs 
    - we fit our statistical learning method on our training observations {($x_1$, $y_1$),($x_2$, $y_2$),...,($x_n$, $y_n$)}, and we obtain the estimate $\hat f $.We can compute $\hat f(x_1) $, $\hat f(x_2) $, ... , $\hat f(x_n) $
    - If these are approximately equal to $y_1$, $y_2$,...,$y_n$ then the training MSE given by above equation is small.
        - However, we are really not interested in whether $\hat f(x_i)$ ≈ $y_i$
        - we want to know whether $\hat f(x_0) $ is approximately equal to $y_0$, where ($x_0$,$y_0$) is a previously unseen test observation not used to train the statistical learning method. 
        - We want to choose the method that gives the <b>lowest test MSE</b>, as opposed to the <b>lowest training MSE</b>.
        - If we have large testing observations then we can compute : <br><img src="img_15.JPG" alt="image" width="150" height="auto"><br>we are interested in method which gives us the above value lowest
        <br>
- If we have test data set : 
    - We can minimise the test MSE and check the approriate statistical learning method 
- If we dont have test data set : 
    -  simply selecting a statistical learning method that minimizes the training MSE. 
    -  fundamental problem with this strategy:
        - there is no guarantee that the method with the lowest training MSE will also have the lowest test MSE.
        - many statistical methods specifcally estimate coefcients so as to minimize the training set MSE.
        - <br> <img src="img_16.JPG" alt="image" width="700" height="auto">
            - Left hand panel 
                - Black curve : true $f$
                - The orange, blue and green curves illustrate three possible estimates for f obtained using methods with increasing levels of fexibility.
                    - Orange line : Linear Regression fit 
                    - Blue and green curves : smoothning splines 
                - It is clear that as the level of fexibility increases, the curves fit the observed data more closely.
            - Right hand panel 
                - Grey  curve : the average training MSE as a function of fexibility, or more formally the degrees of freedom, for a number of smoothing splines.
                    - The degrees of freedom is a quantity that summarizes the fexibility of a curve. 
                - The orange, blue and green squares indicate the MSEs associated with the corresponding curves in the lefthand panel.
                - The training MSE declines monotonically as fexibility increases.
                - true $f$ is non-linear, and so the orange linear fit is not fexible enough to estimate f well. The green curve has the lowest training MSE of all three methods, since it corresponds to the most fexible of the three curves fit in the left-hand panel.
                - Red  curve : the average test MSE as a function of fexibility
                - test MSE initially declines as the level of fexibility increases. However, at some point the test MSE levels of and then starts to increase again
                - the orange and green curves both have high test MSE. The blue curve minimizes the test MSE.
                - The horizontal dashed line indicates Var($\epsilon$), the irreducible error, which corresponds to the lowest achievable test MSE among all possible methods. Hence, the smoothing spline represented by the blue curve is close to optimal.
                
---

NOTE : 
1.  As the fexibility of the statistical learning method increases, we observe a monotone decrease in the training MSE and a U-shape in the test MSE. This is a fundamental property of statistical learning that holds regardless of the particular data set at hand and regardless of the statistical method being used.
2.  As model fexibility increases, the training MSE will decrease, but the test MSE may not.
3.  When a given method yields a small training MSE but a large test MSE, we are said to be overftting the data. This happens because our statistical learning procedure is working too hard to fnd patterns in the training data, and may be picking up some patterns that are just caused by random chance rather than by true properties of the unknown function $f$. 
4. regardless of whether or not overftting has occurred, we almost always expect the training MSE to be smaller than the test MSE because most statistical learning methods either directly or indirectly seek to minimize the training MSE.
5.  Overftting refers specifcally to the case in which a less fexible model would have yielded a smaller test MSE.

---

Few examples :
<br> <img src="img_17.JPG" alt="image" width="700" height="auto"> <img src="img_18.JPG" alt="image" width="700" height="auto">


### <span style="color:blue"> 2.2.2 The Bias-Variance Trade-Off</span>

Observed U-Shape of the test MSE curves : result of two competing properties of statistical learning methods
- the expected test MSE, for a given value $x_0$, can always be decomposed into the sum of three fundamental quantities: 
    - the variance of $\hat f(x_0)$ 
    - the squared bias of $\hat f(x_0)$ 
    - the variance of the error terms $\epsilon$.<br>
<img src="img_19.JPG" alt="image" width="450" height="auto">
- $E \left[ \left( y_0 - \hat{f}(x_0) \right)^2 \right]$ defnes the expected test MSE at $x_0$, expected and refers to the average test MSE that we would obtain if we repeatedly test MSE estimated f using a large number of training sets, and tested each at $x_0$
- The overall expected test MSE can be computed by averaging  $E \left[ \left( y_0 - \hat{f}(x_0) \right)^2 \right]$ over all possible values of x0 in the test set.

####  in order to minimize the expected test error, we need to select a statistical learning method that simultaneously achieves low variance and low bias

---

### <span style="color:orange"> Variance</span>

- amount by which $\hat f$ would change if we estimated it using a diferent training data set.
- Since the training data are used to fit the statistical learning method, <mark>diferent training data sets will result in a diferent $\hat f$. </mark>
- But ideally the estimate for $f$ should not vary too much between training sets. 
- if a <mark>method has high variance then small changes in the training data can result in large changes in $\hat f$. </mark>
- <mark>more fexible statistical methods have higher variance.</mark>

<img src="img_23.JPG" alt="image" width="1000" height="auto"><br>

---

### <span style="color:orange"> Bias</span>

- the error that is introduced by approximating a real-life problem, which may be extremely complicated, by a much simpler model.
- Considering example of Liner regression model :
    - linear regression assumes that there is a linear relationship between $Y$ and $X_1$, $X_2$,...,$X_p$.
    - It is unlikely that any real-life problem truly has such a simple linear relationship, and so performing linear regression will undoubtedly result in some bias in the estimate of $f$.
- <mark>More flexible methods results  in less bias</mark>

---

- as we use more <mark>fexible methods, the variance will increase and the bias will decrease. </mark>
- <mark>The relative rate of change of these two quantities determines whether the test MSE increases or decreases.</mark>
- As we increase the fexibility of a class of methods, the bias tends to initially decrease faster than the variance increases. Consequently, the expected test MSE declines. 
- However, at some point increasing fexibility has little impact on the bias but starts to signifcantly increase the variance. When this happens the test MSE increases.

---

### <span style="color:blue"> 2.2.3 The Classifcation Setting</span>

#### <u> Some modifications in classification setting</u>
- Training observations $\{(x_1, y_1), \ldots, (x_n, y_n)\}$, where now $y_1, \ldots, y_n$ are qualitative.
- Quantification of accuracy : 
    - the $training$ $error$ $rate$ : because it is computed based on the data  that was used to train our classifier.
        - the proportion of mistakes that are made if we apply our estimate  $\hat f$ to the training observations:
        - ### $$\frac{1}{n} \sum_{i=1}^{n} I(y_i \neq \hat{y}_i)$$
            - $\hat y_i$ : The predicted class label for the $i$-th observation using $\hat{f}$.
            - $I(y_i \neq \hat{y}_i)$ : 
                - $Indicator$ $Variable$ : an indicator variable that <mark>equals 1 if $y_i \neq \hat{y}_i$</mark> and <mark>0 if $y_i = \hat{y}_i$.</mark> 
                - <mark>Indicator variable If $I(y_i \neq \hat{y}_i) = 0$ then the $i$th observation was classified correctly by our classification method; otherwise it was misclassified.</mark>
    - the $testing$ $error$ $rate$ : associated with the test observations of the form : $(x_0, y_0)$
        - ### $$\text{Ave}(I(y_0 \neq \hat{y}_0))$$ 
            - $\hat{y}_0$ :  is the predicted class label that results from applying the classifier to the test observation with predictor $x_0$.

---

#### Good classifier : Test error rate is small

---



### <span style="color:orange"> The Bayes Classifer</span>

- very simple classifer that assigns each observation to the most likely class, given its predictor values.
- simply assign a test observation with predictor vector x0 to the class j for which 
#### $$ Pr(Y = j | X = x_0) $$  
 is largest.
- Above is conditional probablity : It is the probability that $Y$ = $j$ , given that $X$ = $x_0$
- In a <mark>two-class problem</mark> where there are only two possible response values, say class 1 or class 2, the <mark>Bayes classifier corresponds to predicting class one if $Pr(Y = 1|X = x_0) > 0.5$, and class two otherwise.</mark>

<img src="img_24.JPG" alt="image" width="900" height="auto"><br>
<i>A simulated data set consisting of 100 observations in each of
two groups, indicated in blue and in orange. The purple dashed line represents
the Bayes decision boundary. The orange background grid indicates the region
in which a test observation will be assigned to the orange class, and the blue
background grid indicates the region in which a test observation will be assigned
to the blue class.</i>

- The Bayes classifier produces the lowest possible test error rate, called the <mark>Bayes error rate.</mark>
- Since the Bayes classifier will always choose the class Bayes error rate for which $Pr(Y = j|X = x_0)$ is largest, the error rate will be $1 - \max_j Pr(Y = j|X = x_0)$ at $X = x_0$. 
- In general, the overall Bayes error rate is given by 
### $$1 - E[\max_j Pr(Y = j|X)]$$
 ,where the expectation averages the probability over all possible values of $X$. 
- For our simulated data, the Bayes error rate is 0.133. It is greater than zero because the classes overlap in the true population, which implies that $\max_j Pr(Y = j|X = x_0) < 1$ for some values of $x_0$. The Bayes error rate is analogous to the irreducible error discussed earlier.


### <span style="color:orange"> K-Nearest Neighbors</span>

- for real data, we do not know the conditional distribution of Y given X, and so computing the Bayes classifer is impossible.
- Given positive integer $K$ and a test observation $x_0$, the KNN classifier first <mark>identifies the $K$ points in the training data that are closest to $x_0$, represented by $N_0$. </mark>
- It then estimates the <mark>conditional probability for class $j$ as the fraction of points in $N_0$ whose response values equal $j$:
$$Pr(Y = j|X = x_0) = \frac{1}{K} \sum_{i \in N_0} I(y_i = j)$$</mark>
- KNN classifes the test observation x0 to the class with the largest probability


<img src="img_25.JPG" alt="image" width="600" height="auto"><br>
<i>The KNN approach, using K = 3, is illustrated in a simple
situation with six blue observations and six orange observations. Left: a test
observation at which a predicted class label is desired is shown as a black cross.
The three closest points to the test observation are identifed, and it is predicted
that the test observation belongs to the most commonly-occurring class, in this
case blue. Right: The KNN decision boundary for this example is shown in black.
The blue grid indicates the region in which a test observation will be assigned to
the blue class, and the orange grid indicates the region in which it will be assigned
to the orange class.</i>

- choosing the correct level of fexibility is critical to the success of any statistical learning method. The bias-variance tradeof, and the resulting U-shape in the test error, can make this a difcult task.

<img src="img_26.JPG" alt="image" width="600" height="auto"><br>
<i>With
K = 1, the decision boundary is overly fexible, while with K = 100 it is not
sufciently fexible. The Bayes decision boundary is shown as a purple dashed
line. and black is for KNN

<img src="img_27.JPG" alt="image" width="600" height="auto"><br>
<i>The KNN training error rate (blue, 200 observations) and test
error rate (orange, 5,000 observations) on the data from Figure 2.13, as the level
of fexibility (assessed using 1/K on the log scale) increases, or equivalently as
the number of neighbors K decreases. The black dashed line indicates the Bayes
error rate. The jumpiness of the curves is due to the small size of the training
data set.

## <span style="color:red"> 2.3 Lab: Introduction to Python</span>.

### <span style="color:blue"> 2.3.1 Getting Started</span>.

### <span style="color:blue"> 2.3.2 Basic Commands</span>.

In [3]:
print('fit a model with', 11, 'variables')

fit a model with 11 variables


In [4]:
print?

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [5]:
x = [3, 4, 5]
x

[3, 4, 5]

In [6]:
y = [4, 9, 7]
x+y

[3, 4, 5, 4, 9, 7]

### <span style="color:blue"> 2.3.3 Introduction to Numerical Python</span>.

In [7]:
import numpy as np

In [8]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

In [9]:
x + y

array([ 7, 13, 12])

In [10]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [11]:
x.ndim

2

In [12]:
x.dtype

dtype('int32')

In [13]:
np.array([[1, 2], [3.0, 4]]).dtype

dtype('float64')

In [14]:
 np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (

#### We could create a foating point array by passing a dtype argument into `np.array()`.

In [15]:
 np.array([[1, 2], [3, 4]], float).dtype

dtype('float64')

#### The array x is two-dimensional. We can fnd out the number of rows and columns by looking at its `shape` attribute

In [16]:
x.shape

(2, 2)

A method is a function that is associated with an object. For instance, method given an array `x`, the expression `x.sum()` sums all of its elements, using the `sum()` method for arrays. The call `x.sum()` automatically provides `x` as the `.sum()` frst argument to its `sum()` method

In [17]:
x = np.array([1, 2, 3, 4]).sum()
x

10

In [18]:
sum?

Signature: sum(iterable, /, start=0)
Docstring:
Return the sum of a 'start' value (default: 0) plus an iterable of numbers

When the iterable is empty, return the start value.
This function is intended specifically for use with numeric values and may
reject non-numeric types.
Type:      builtin_function_or_method

In [19]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

As another example, the `reshape()` method returns a new array with the same elements as `x`, but a diferent shape. We do this by passing in a `tuple`in our call to `reshape()`, in this case `(2, 3)`. This `tuple` specifes that we would like to create a two-dimensional array with 2 rows and 3 columns.2 In what follows, the `\n` character creates a new line

In [20]:
x = np.array([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape((2, 3))
print('reshaped x:\n', x_reshape)

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [21]:
x_reshape[1, 2]

6

In [22]:
x_reshape[0, 0] = 5
x_reshape

array([[5, 2, 3],
       [4, 5, 6]])

In [23]:
my_tuple = (3, 4, 5)
my_tuple[0] = 2

TypeError: 'tuple' object does not support item assignment

In [24]:
x_reshape.shape

(2, 3)

In [25]:
x_reshape.ndim

2

In [26]:
 x_reshape.T

array([[5, 4],
       [2, 5],
       [3, 6]])

In [27]:
x_reshape.T.shape

(3, 2)

In [28]:
 np.sqrt(x)

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [29]:
x**2

array([25,  4,  9, 16, 25, 36])

In [30]:
x

array([5, 2, 3, 4, 5, 6])

In [31]:
x = np.random.normal(size=50)
x

array([-0.58337834,  0.15025811, -1.25001053,  0.50727696,  0.77981077,
        0.43181605,  0.34985758, -1.10198146, -0.07578567,  1.01083682,
        0.68567432, -1.22068069,  1.391352  , -0.13935186, -0.90872787,
        0.16922581,  0.10220595,  0.46602399,  0.63387923, -0.54590838,
       -1.55782983,  1.09908744, -1.10637733, -0.03283059, -0.94137151,
       -0.62905054, -0.1861669 , -0.91790425, -0.33250818, -2.2507106 ,
        0.14063771,  0.72613496, -0.77030007,  0.8188484 ,  0.70971799,
        0.04841052,  0.44419468, -1.43543034, -0.36806104,  1.18264541,
       -1.91208697, -0.15231121, -0.67119985, -0.08796113,  0.28885291,
       -0.4762306 , -0.47246805, -1.25829248,  0.02260674,  0.31407923])

In [32]:
y = x + np.random.normal(loc=50, scale=1, size=50)

The np.corrcoef() function computes the correlation matrix between x and np.corrcoef()
y. The of-diagonal elements give the correlation between x and y.

In [34]:
np.corrcoef(x, y)

array([[1.        , 0.65017786],
       [0.65017786, 1.        ]])

In [38]:
print(np.random.normal(scale=1, size=4))
print(np.random.normal(scale=1, size=2))

[ 1.48356396  0.76610779 -0.63922132  1.35222002]
[2.27047633 2.12633888]


In [47]:
rng = np.random.default_rng(100)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(100)
print(rng2.normal(scale=5, size=2))

[-5.78774824  1.44877901]
[-5.78774824  1.44877901]
